### PR TITLE
[WIP] Update README.md

### PR DESCRIPTION
**Pull request by chrisarcand**

### CODE REVIEW

**Comment by chrisarcand** [comment]
@notchrisarcand add_label wip

**Comment by notchrisarcand** [comment]
<rubocop />Checked commit https://github.com/matoska/sandbox/commit/82ad3b8bd2463401b319ee3b875eb268afa1d42e with ruby 2.3.3, rubocop 0.47.1, and haml-lint 0.20.0
0 files checked, 0 offenses detected
Everything looks good. :star:

**Comment by notchrisarcand** [comment]
@ Cannot apply the following label because they are not recognized: wip

**Comment by chrisarcand** [comment]
@notchrisarcand add_labels wip, bug

**Comment by notchrisarcand** [comment]
@ Cannot apply the following label because they are not recognized: wip

**Comment by chrisarcand** [comment]
@notchrisarcand add_labels wip, bug

**Comment by notchrisarcand** [comment]
@chrisarcand Cannot apply the following label because they are not recognized: wip

**Comment by chrisarcand** [comment]
@notchrisarcand remove_labels bug

**Comment by chrisarcand** [comment]
@notchrisarcand add_labels wip, bug

**Comment by chrisarcand** [comment]
@notchrisarcand remove_label wip

**Comment by chrisarcand** [comment]
@notchrisarcand add_labels wip, bug

**Comment by chrisarcand** [comment]
@notchrisarcand remove_label wip

**Comment by chrisarcand** [comment]
@notchrisarcand add_labels wip, bug

**Comment by chrisarcand** [comment]
@notchrisarcand remove_label wip

**Comment by chrisarcand** [comment]
@notchrisarcand add_labels wip, asdf

**Comment by notchrisarcand** [comment]
@chrisarcand Cannot apply the following label because they are not recognized: asdf

**Pull request closed without merging**
