### PR TITLE
asdfasdf

### PR DESCRIPTION
**Pull request by chrisarcand**

### CODE REVIEW

**Comment by notchrisarcand** [comment]
<rubocop />Checked commit https://github.com/chrisarcand/sandbox/commit/0a9a88cc8dcf8623e8c7555a9d6340b4fd8ddeb5 with ruby 2.3.3, rubocop 0.47.1, and haml-lint 0.20.0
0 files checked, 0 offenses detected
Everything looks good. :cookie:

**Comment by notchrisarcand** [comment]
<rubocop />Checked commits https://github.com/chrisarcand/sandbox/compare/0a9a88cc8dcf8623e8c7555a9d6340b4fd8ddeb5~...3d47fb1953b7459c71c0fe0508f19d60a35a1ab8 with ruby 2.3.3, rubocop 0.47.1, and haml-lint 0.20.0
0 files checked, 0 offenses detected
Everything looks good. :cake:

**Comment by notchrisarcand** [comment]
<rubocop />Checked commits https://github.com/chrisarcand/sandbox/compare/0a9a88cc8dcf8623e8c7555a9d6340b4fd8ddeb5~...b6d41d8955a38cd8ea2cd97c42c214285eb0729f with ruby 2.3.3, rubocop 0.47.1, and haml-lint 0.20.0
0 files checked, 0 offenses detected
Everything looks good. :+1:

**Comment by notchrisarcand** [comment]
<rubocop />Checked commits https://github.com/chrisarcand/sandbox/compare/0a9a88cc8dcf8623e8c7555a9d6340b4fd8ddeb5~...2f318f15923d43ed99754176ea01d5199064a3ff with ruby 2.3.3, rubocop 0.47.1, and haml-lint 0.20.0
0 files checked, 0 offenses detected
Everything looks good. :cookie:

**Comment by notchrisarcand** [comment]
<rubocop />Checked commits https://github.com/chrisarcand/sandbox/compare/0a9a88cc8dcf8623e8c7555a9d6340b4fd8ddeb5~...ab733fcb60f477f65bf64314fa19e6a422b75779 with ruby 2.3.3, rubocop 0.47.1, and haml-lint 0.20.0
0 files checked, 0 offenses detected
Everything looks good. :+1:

**Comment by notchrisarcand** [comment]
<rubocop />Checked commits https://github.com/chrisarcand/sandbox/compare/0a9a88cc8dcf8623e8c7555a9d6340b4fd8ddeb5~...6514595139135368e19ec4632160eed1be90b8bf with ruby 2.3.3, rubocop 0.47.1, and haml-lint 0.20.0
0 files checked, 0 offenses detected
Everything looks good. :cookie:

**Comment by chrisarcand** [comment]
@notchrisarcand add_label wip

**Comment by notchrisarcand** [comment]
<rubocop />Checked commits https://github.com/chrisarcand/sandbox/compare/0a9a88cc8dcf8623e8c7555a9d6340b4fd8ddeb5~...b4c26c71a6635818d0b92e87f4e3866f45d6b4b4 with ruby 2.3.3, rubocop 0.47.1, and haml-lint 0.20.0
0 files checked, 0 offenses detected
Everything looks good. :cookie:

**Comment by chrisarcand** [comment]
@notchrisarcand add_label bug

**Comment by chrisarcand** [comment]
@notchrisarcand add_label bug

**Comment by notchrisarcand** [comment]
<rubocop />Checked commits https://github.com/chrisarcand/sandbox/compare/0a9a88cc8dcf8623e8c7555a9d6340b4fd8ddeb5~...0af2b752fe764f5a298ff8e9dfa7f023e9504959 with ruby 2.3.3, rubocop 0.47.1, and haml-lint 0.20.0
0 files checked, 0 offenses detected
Everything looks good. :cookie:

**Comment by notchrisarcand** [comment]
<rubocop />Checked commits https://github.com/chrisarcand/sandbox/compare/0a9a88cc8dcf8623e8c7555a9d6340b4fd8ddeb5~...0e6f1073c6d624e72b6c274131c96bd22f8bd2be with ruby 2.3.3, rubocop 0.47.1, and haml-lint 0.20.0
0 files checked, 0 offenses detected
Everything looks good. :+1:

**Comment by chrisarcand** [comment]
@notchrisarcand add_label bug

**Comment by chrisarcand** [comment]
@notchrisarcand add_label bug

**Comment by chrisarcand** [comment]
@notchrisarcand add_label bug

**Comment by chrisarcand** [comment]
@notchrisarcand add_label bug

**Comment by chrisarcand** [comment]
@notchrisarcand remove_label bug

**Comment by chrisarcand** [comment]
@notchrisarcand remove_label bug

**Comment by chrisarcand** [comment]
@notchrisarcand remove_label bug

**Comment by chrisarcand** [comment]
@notchrisarcand add_labels invalid, blahblahblah

**Comment by notchrisarcand** [comment]
@chrisarcand Cannot apply the following label because they are not recognized: blahblahblah

**Comment by chrisarcand** [comment]
@notchrisarcand add_labels Wip, enhancement, blahblahblah

**Comment by notchrisarcand** [comment]
@chrisarcand Cannot apply the following label because they are not recognized: blahblahblah

**Comment by chrisarcand** [comment]
@notchrisarcand remove_labels doesntexist, wip, enhancement

**Comment by notchrisarcand** [comment]
@chrisarcand Cannot remove the following label because they are not recognized: doesntexist

**Comment by chrisarcand** [comment]
@notchrisarcand remove_labels wip

**Comment by chrisarcand** [comment]
@notchrisarcand remove_labels wip

**Comment by chrisarcand** [comment]
@notchrisarcand remove_labels asdf, invalid

**Comment by notchrisarcand** [comment]
<github-pr-commenter-batch />Some comments on commits https://github.com/chrisarcand/sandbox/compare/0a9a88cc8dcf8623e8c7555a9d6340b4fd8ddeb5~...7aff85b4dd316affb1ed70ad934dd3e298e99d25

**db/migrate/asdf.rb**
- [ ] :bomb: :boom: :fire: :fire_engine: - Bad Migration Timestamp

**Comment by notchrisarcand** [comment]
<github-pr-commenter-batch />Some comments on commits https://github.com/chrisarcand/sandbox/compare/0a9a88cc8dcf8623e8c7555a9d6340b4fd8ddeb5~...7aff85b4dd316affb1ed70ad934dd3e298e99d25

**db/migrate/asdf.rb**
- [ ] :bomb: :boom: :fire: :fire_engine: - Bad Migration Timestamp

**Comment by notchrisarcand** [comment]
<rubocop />Checked commits https://github.com/chrisarcand/sandbox/compare/0a9a88cc8dcf8623e8c7555a9d6340b4fd8ddeb5~...7aff85b4dd316affb1ed70ad934dd3e298e99d25 with ruby 2.3.3, rubocop 0.47.1, and haml-lint 0.20.0
2 files checked, 1 offense detected

**\*\***
- [ ] :bomb: :boom: :fire: :fire_engine: - Linter/Rubocop - missing config files

**Comment by notchrisarcand** [comment]
<github-pr-commenter-batch />Some comments on commits https://github.com/chrisarcand/sandbox/compare/0a9a88cc8dcf8623e8c7555a9d6340b4fd8ddeb5~...eb01becb8518194c3c44af66e5e5367908a7d07f

**db/migrate/asdf.rb**
- [ ] :bomb: :boom: :fire: :fire_engine: - Bad Migration Timestamp

**Comment by notchrisarcand** [comment]
<rubocop />Checked commits https://github.com/chrisarcand/sandbox/compare/0a9a88cc8dcf8623e8c7555a9d6340b4fd8ddeb5~...eb01becb8518194c3c44af66e5e5367908a7d07f with ruby 2.3.3, rubocop 0.47.1, and haml-lint 0.20.0
2 files checked, 1 offense detected

**\*\***
- [ ] :bomb: :boom: :fire: :fire_engine: - Linter/Rubocop - missing config files

**Comment by chrisarcand** [comment]
@notchrisarcand add_labels bug, asdfasdf

**Comment by notchrisarcand** [comment]
@chrisarcand Cannot apply the following label because they are not recognized: asdfasdf

**Comment by chrisarcand** [comment]
@notchrisarcand add_labels bug, asdfasdf

**Comment by notchrisarcand** [comment]
@chrisarcand Cannot apply the following label because they are not recognized: asdfasdf

**Comment by chrisarcand** [comment]
@notchrisarcand add_labels bug, asdfasdf

**Comment by notchrisarcand** [comment]
@chrisarcand Cannot apply the following label because they are not recognized: asdfasdf

**Comment by chrisarcand** [comment]
@notchrisarcand add_labels bug, asdfasdf

**Comment by notchrisarcand** [comment]
@chrisarcand Cannot apply the following label because they are not recognized: asdfasdf

**Comment by chrisarcand** [comment]
@notchrisarcand add_labels bug, asdfasdf

**Comment by notchrisarcand** [comment]
@chrisarcand Cannot apply the following label because they are not recognized: asdfasdf

**Comment by chrisarcand** [comment]
@notchrisarcand remove_labels bug, asdfasdfasdf

**Comment by notchrisarcand** [comment]
@chrisarcand Cannot remove the following label because they are not recognized: asdfasdfasdf

**Comment by chrisarcand** [comment]
@notchrisarcand remove_labels bug, asdfasdfasdf

**Comment by notchrisarcand** [comment]
@chrisarcand Cannot remove the following label because they are not recognized: asdfasdfasdf

**Comment by chrisarcand** [comment]
@notchrisarcand remove_labels bug, asdfasdfasdf

**Comment by notchrisarcand** [comment]
@chrisarcand Cannot remove the following label because they are not recognized: asdfasdfasdf

**Comment by chrisarcand** [comment]
@notchrisarcand remove_labels bug

**Comment by chrisarcand** [comment]
@notchrisarcand add_labels bug, asdfasdf

**Comment by notchrisarcand** [comment]
@chrisarcand Cannot apply the following label because they are not recognized: asdfasdf

**Comment by chrisarcand** [comment]
@notchrisarcand add_labels bug, asdfasdf

**Comment by notchrisarcand** [comment]
@chrisarcand Cannot apply the following label because they are not recognized: asdfasdf

**Comment by notchrisarcand** [comment]
<rubocop />Checked commits https://github.com/chrisarcand/sandbox/compare/0a9a88cc8dcf8623e8c7555a9d6340b4fd8ddeb5~...d3496b16e90a3b976a82ab3d6dd6b1f9d3504c11 with ruby 2.3.3, rubocop 0.47.1, and haml-lint 0.20.0
2 files checked, 1 offense detected

**\*\***
- [ ] :bomb: :boom: :fire: :fire_engine: - Linter/Rubocop - missing config files

**Comment by notchrisarcand** [comment]
<github-pr-commenter-batch />Some comments on commits https://github.com/chrisarcand/sandbox/compare/0a9a88cc8dcf8623e8c7555a9d6340b4fd8ddeb5~...d3496b16e90a3b976a82ab3d6dd6b1f9d3504c11

**db/migrate/asdf.rb**
- [ ] :bomb: :boom: :fire: :fire_engine: - Bad Migration Timestamp

**Comment by notchrisarcand** [comment]
<rubocop />Checked commits https://github.com/chrisarcand/sandbox/compare/0a9a88cc8dcf8623e8c7555a9d6340b4fd8ddeb5~...344dceea8b83879712358d42d2c18c98f9f20a09 with ruby 2.3.3, rubocop 0.47.1, and haml-lint 0.20.0
2 files checked, 1 offense detected

**\*\***
- [ ] :bomb: :boom: :fire: :fire_engine: - Linter/Rubocop - missing config files

**Comment by notchrisarcand** [comment]
<github-pr-commenter-batch />Some comments on commits https://github.com/chrisarcand/sandbox/compare/0a9a88cc8dcf8623e8c7555a9d6340b4fd8ddeb5~...344dceea8b83879712358d42d2c18c98f9f20a09

**db/migrate/asdf.rb**
- [ ] :bomb: :boom: :fire: :fire_engine: - Bad Migration Timestamp

**Comment by notchrisarcand** [comment]
<rubocop />Checked commits https://github.com/chrisarcand/sandbox/compare/0a9a88cc8dcf8623e8c7555a9d6340b4fd8ddeb5~...941ce69526a5320dcac9241e108c15ac00340cde with ruby 2.3.3, rubocop 0.47.1, and haml-lint 0.20.0
2 files checked, 1 offense detected

**\*\***
- [ ] :bomb: :boom: :fire: :fire_engine: - Linter/Rubocop - missing config files

**Comment by notchrisarcand** [comment]
<github-pr-commenter-batch />Some comments on commits https://github.com/chrisarcand/sandbox/compare/0a9a88cc8dcf8623e8c7555a9d6340b4fd8ddeb5~...941ce69526a5320dcac9241e108c15ac00340cde

**db/migrate/asdf.rb**
- [ ] :bomb: :boom: :fire: :fire_engine: - Bad Migration Timestamp

**Comment by notchrisarcand** [comment]
<github-pr-commenter-batch />Some comments on commits https://github.com/chrisarcand/sandbox/compare/0a9a88cc8dcf8623e8c7555a9d6340b4fd8ddeb5~...6b63a7b189abf4103397f9e8cbe504fc8c47425f

**db/migrate/asdf.rb**
- [ ] :bomb: :boom: :fire: :fire_engine: - Bad Migration Timestamp

**Comment by notchrisarcand** [comment]
<rubocop />Checked commits https://github.com/chrisarcand/sandbox/compare/0a9a88cc8dcf8623e8c7555a9d6340b4fd8ddeb5~...6b63a7b189abf4103397f9e8cbe504fc8c47425f with ruby 2.3.3, rubocop 0.47.1, and haml-lint 0.20.0
2 files checked, 1 offense detected

**\*\***
- [ ] :bomb: :boom: :fire: :fire_engine: - Linter/Rubocop - missing config files

**Comment by notchrisarcand** [comment]
test

**Pull request closed without merging**
